### ISSUE TITLE
http://www.inhouseprotocols.com/publications.php

### ISSUE THREAD

**Issue by Anonim-tech** [arunhpatil/GoogleScholar#1]
Can I share this code? I'm confused about making it. thank you

http://www.inhouseprotocols.com/publications.php

**Comment by arunhpatil** [comment]
@Anonim-tech, you can find the scripts here. Rename the extensions to php. Note the line graph and table is from GoogleScholar.php otherwise I have formatted the rest on publications.php. Hope this helps. Let me know if you have any queries. 

[GoogleScholar.txt](https://github.com/arunhpatil/GoogleScholar/files/3991946/GoogleScholar.txt)
[publications.txt](https://github.com/arunhpatil/GoogleScholar/files/3991947/publications.txt)
